# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prostheticarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Prosthetic_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 780)
        MainWindow.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), "
            "stop:0.0199005 rgba(0, 0, 0, 200), stop:0.995025  rgba(11, 19, 43, 80), stop:1 rgba(11, 19, 43, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 110, 421, 641))
        self.frame.setStyleSheet("background-color: rgb(28, 37, 65, 85);\n"
                                 "border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.open_button = QtWidgets.QPushButton(self.frame)
        self.open_button.setGeometry(QtCore.QRect(70, 450, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.open_button.setFont(font)
        self.open_button.setStyleSheet("background-color: rgb(91,192,190);\n"
                                       "border-radius: 20px;")
        self.open_button.setObjectName("open_button")
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setGeometry(QtCore.QRect(70, 540, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("background-color: rgb(91,192,190);\n"
                                        "border-radius: 20px;")
        self.close_button.setObjectName("close_button")
        self.arm_state = QtWidgets.QLabel(self.frame)
        self.arm_state.setGeometry(QtCore.QRect(70, 60, 281, 261))
        font.setPointSize(20)

        font.setBold(True)
        self.arm_state.setStyleSheet("color:white;")
        self.arm_state.setAlignment(QtCore.Qt.AlignCenter)
        self.arm_state.setFont(font)

        self.arm_state.setText("")
        self.arm_state.setObjectName("arm_state")
        self.predictions_button = QtWidgets.QPushButton(self.frame)
        self.predictions_button.setGeometry(QtCore.QRect(70, 360, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.predictions_button.setFont(font)
        self.predictions_button.setStyleSheet("background-color: rgb(91,192,190);\n"
                                              "border-radius: 20px;")
        self.predictions_button.setObjectName("predictions_button")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(120, 30, 781, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(24)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color: rgb(111, 255, 233);")
        self.title_label.setObjectName("title_label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(530, 110, 421, 641))
        self.frame_2.setStyleSheet("background-color: rgb(28, 37, 65, 85);\n"
                                   "border-radius: 20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.connect_button = QtWidgets.QPushButton(self.frame_2)
        self.connect_button.setGeometry(QtCore.QRect(70, 540, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.connect_button.setFont(font)
        self.connect_button.setStyleSheet("background-color: rgb(91,192,190);\n"
                                          "border-radius: 20px;")
        self.connect_button.setObjectName("connect_button")
        self.serial_label = QtWidgets.QLabel(self.frame_2)
        self.serial_label.setGeometry(QtCore.QRect(70, 60, 281, 261))
        self.serial_label.setText("")
        self.serial_label.setObjectName("serial_label")
        self.scan_button = QtWidgets.QPushButton(self.frame_2)
        self.scan_button.setGeometry(QtCore.QRect(70, 360, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.scan_button.setFont(font)
        self.scan_button.setStyleSheet("background-color: rgb(91,192,190);\n"
                                       "border-radius: 20px;")
        self.scan_button.setObjectName("scan_button")
        self.ports_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.ports_comboBox.setGeometry(QtCore.QRect(70, 450, 271, 61))
        self.ports_comboBox.setStyleSheet("background-color: rgb(91,192,190);\n"
                                          "border-radius: 20px;")
        self.ports_comboBox.setObjectName("ports_comboBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_button.setText(_translate("MainWindow", "Grasp"))
        self.close_button.setText(_translate("MainWindow", "Release"))
        self.predictions_button.setText(_translate("MainWindow", "Predict"))
        self.title_label.setText(_translate("MainWindow", "Mind Controlled Prosthetic Arm"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.scan_button.setText(_translate("MainWindow", "Scan"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Prosthetic_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
